// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Proyecto_BK.Entities.Entities
{
    public partial class tbPromocionesPorBebidas
    {
        public int Pbeb_Id { get; set; }
        public int? Prom_Id { get; set; }
        public int? Bebi_Id { get; set; }

        public virtual tbBebidas Bebi { get; set; }
        public virtual tbPromociones Prom { get; set; }
    }
}