// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Proyecto_BK.Entities
{
    public partial class tbCombo
    {
        public int Comb_Id { get; set; }
        public int? Alim_Id { get; set; }
        public int? Bebi_Id { get; set; }
        public int? Comp_Id { get; set; }
        public int? Post_Id { get; set; }
        public int? Comb_Usua_Creacion { get; set; }
        public DateTime? Comb_Fecha_Creacion { get; set; }
        public int? Comb_Usua_Modifica { get; set; }
        public DateTime? Comb_Fecha_Modificacion { get; set; }
        public bool? Comb_Estado { get; set; }
        public string Comb_Descripcion { get; set; }
        public decimal? Comb_Precio { get; set; }
        public string Comb_Imagen { get; set; }
    }
}