// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Proyecto_BK.Entities
{
    public partial class tbCombo
    {
        public int Comb_Id { get; set; }
        public int? Alim_Id { get; set; }
        public int? Bebi_Id { get; set; }
        public int? Comp_Id { get; set; }
        public int? Post_Id { get; set; }
        public int? Comb_Usua_Creacion { get; set; }
        public DateTime? Comb_Fecha_Creacion { get; set; }
        public int? Comb_Usua_Modifica { get; set; }
        public DateTime? Comb_Fecha_Modificacion { get; set; }
        public bool? Comb_Estado { get; set; }
        public string Comb_Descripcion { get; set; }
        public decimal? Comb_Precio { get; set; }
        public string Comb_Imagen { get; set; }
        [NotMapped]
        public string Usua_Creacion { get; set; }
        [NotMapped]
        public string Usua_Modifica { get; set; }
        [NotMapped]
        public string Bebi_Descripcion { get; set; }
        [NotMapped]
        public string Post_Descripcion { get; set; }
        [NotMapped]
        public string Comp_Descripcion { get; set; }
        [NotMapped]
        public string Alim_Descripcion { get; set; }

        [NotMapped]
        public string Usua_Usuario { get; set; }
        public int TotalPedidosCombos { get; set; }
        [NotMapped]
        public int Paqe_Id { get; set; }
        [NotMapped]
        public string Paqe_Descripcion { get; set; }
        [NotMapped]
        public int TotalPedidosPaquetes { get; set; }
        [NotMapped]
        public int TotalPedidosAlimentos { get; set; }
        [NotMapped]
        public int TotalPedidosPostres { get; set; }
        [NotMapped]
        public decimal precio { get; set; }

        public virtual tbAlimentos Alim { get; set; }
        public virtual tbBebidas Bebi { get; set; }
        public virtual tbUsuarios Comb_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Comb_Usua_ModificaNavigation { get; set; }
        public virtual tbComplementos Comp { get; set; }
        public virtual tbPostres Post { get; set; }
        [NotMapped]

        public string text { get; set; }
        [NotMapped]
        public int value { get; set; }
        [NotMapped]

        public string image { get; set; }
    }
}