// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Proyecto_BK.Entities
{
    public partial class tbDias
    {
        public tbDias()
        {
            tbPromociones = new HashSet<tbPromociones>();
        }

        public int Dias_Id { get; set; }
        public string Dias_Descripcion { get; set; }

        public virtual ICollection<tbPromociones> tbPromociones { get; set; }
    }
}