// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Proyecto_BK.Entities
{
    public partial class tbFactura
    {
        public tbFactura()
        {
            tbFacturaDetalle = new HashSet<tbFacturaDetalle>();
        }

        public int Fact_Id { get; set; }
        public int? Sucu_Id { get; set; }
        public int? Empl_Id { get; set; }
        public string Fact_Fecha { get; set; }
        public decimal? Fact_Total { get; set; }
        public int? Fact_Usua_Creacion { get; set; }
        public DateTime? Fact_Fecha_Creacion { get; set; }
        public bool? Fact_Estado { get; set; }
        public string Clie_Identidad { get; set; }
        public string Clie_Nombre { get; set; }
        [NotMapped]
        public string Alim_Descripcion { get; set; }
        [NotMapped]
        public string Alim_Precio { get; set; }
        [NotMapped]
        public string Alim_Imagen { get; set; }

        [NotMapped]
        public string Bebi_Descripcion { get; set; }
        [NotMapped]
        public string Bebi_Precio { get; set; }
        [NotMapped]
        public string Bebi_Imagen { get; set; }

        [NotMapped]
        public string Comp_Descripcion { get; set; }
        [NotMapped]
        public string Comp_Precio { get; set; }
        [NotMapped]
        public string Comp_Imagen { get; set; }

        [NotMapped]
        public string Post_Descripcion { get; set; }
        [NotMapped]
        public string Post_Precio { get; set; }
        [NotMapped]
        public string Post_Imagen { get; set; }
        [NotMapped]
        public string Sucu_Descripcion { get; set; }
        [NotMapped]
        public string Empleado { get; set; }


        [NotMapped]
        public string CantidadVentas { get; set; }
        
        [NotMapped]
        public string Usua_Usuario { get; set; }
        public virtual tbEmpleados Empl { get; set; }
        public virtual tbUsuarios Fact_Usua_CreacionNavigation { get; set; }
        public virtual tbSucursales Sucu { get; set; }
        public virtual ICollection<tbFacturaDetalle> tbFacturaDetalle { get; set; }
    }
}