// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Proyecto_BK.Entities
{
    public partial class tbFacturaDetalle
    {
        public int FaDe_Id { get; set; }
        public int? Fact_Id { get; set; }
        public int? FaDe_Cantidad { get; set; }
        public decimal? FaDe_Subtotal { get; set; }
        public string FaDe_Ident { get; set; }
        public int? FaDe_ProdId { get; set; }

        [NotMapped]
        public string Sucursal { get; set; }
        [NotMapped]
        public string Empleado { get; set; }
        [NotMapped]
        public string Producto { get; set; }
        [NotMapped]
        public string Tipo { get; set; }

        [NotMapped]
        public string Cantidad { get; set; }
        [NotMapped]
        public string Subtotal { get; set; }
        public virtual tbFactura Fact { get; set; }
    }
}