// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Proyecto_BK.Entities
{
    public partial class tbPromocionesPorPostres
    {
        public int Ppos_Id { get; set; }
        public int? Prom_Id { get; set; }
        public int? Post_Id { get; set; }

        public virtual tbPostres Post { get; set; }
        public virtual tbPromociones Prom { get; set; }
    }
}