// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Proyecto_BK.Entities
{
    public partial class tbPromocionesPorComplementos
    {
        public int Pcom_Id { get; set; }
        public int? Prom_Id { get; set; }
        public int? Comp_Id { get; set; }
        [NotMapped]
        public string Comp_Descripcion { get; set; }
        public virtual tbComplementos Comp { get; set; }
        public virtual tbPromociones Prom { get; set; }
    }
}